### ISSUE TITLE
Electrum Wallet (Light) Client/Server

### ISSUE THREAD

**Issue by smogm** [project-ecc/issues#2]
What about hosting 1 - 2 ElectrumX server nodes from
https://github.com/kyuupichan/electrumx/

And deliver an ECC Electrum client to the users:
https://github.com/kyuupichan/electrum

Guess there only some minor changes necessary (e.g. coin parameters etc.)

https://electrumx.readthedocs.io/en/latest/HOWTO.html

seems to be easy
run **as root**:

```
apt install phython3.6 or higher
apt install python3-aiohttp
apt install python3-pip

pip3 install pylru plyvel
```

then run **as normal user**:

```
git clone https://github.com/kyuupichan/electrumx.git
cd electrumx
python3 setup.py install
```

Edit: Got it working on debian stretch like this:
Using python3.6 from here: https://github.com/chriskuehl/python3.6-debian-stretch

Then execute this:
```
mkdir pyvirt
cd pyvirt
git clone https://github.com/kyuupichan/electrumx.git
virtualenv -p python3.6 .
source bin/activate
pip install pylru plyvel aiorpcx aiohttp
cd electrumx
mkdir dbdir # to store utxo and blockchain db
```

Those env variables have to be set before you run the server:
```
export DB_DIRECTORY=dbdir
export DAEMON_URL=http://<rpcusername>:<rpcpassword>@<rpchostname>:<rpcport>/ #RPC data of the wallet daemon
export COIN=ECCoin
```
Then start the server with:

```
./electrumx_server
```

**Comment by HenryYoung42** [comment]
The coin specific definitions go here https://github.com/kyuupichan/electrumx/blob/master/electrumx/lib/coins.py - it's a shame the developer didn't drop these into a config file, but some coin specifics seem to entail overriding class methods.

**Comment by HenryYoung42** [comment]
Python 3.6 means Ubuntu 18 - or some sysadmin hacking on stable Ubuntu 16 nodes which I'd prefer to avoid. So I'm down to only two nodes I can set this up on, unless I expand my cloud empire ...

**Comment by smogm** [comment]
Two nodes should be enough for the beginning :+1: 

Also interesting for later client side implementation: https://github.com/you21979/node-electrum-client

Could be used as web-wallet frontend replacement

**Comment by smogm** [comment]
With this additional class to the lib/coins.py file the electrumx_server seems at least to start without any errors:

```
class ECCoin(Coin):
    NAME = "ECCoin"
    SHORTNAME = "ECC"
    NET = "mainnet"
    DESERIALIZER = lib_tx.DeserializerTxTime
    XPUB_VERBYTES = bytes.fromhex("0488b21e")
    XPRV_VERBYTES = bytes.fromhex("0488ade4")
    P2PKH_VERBYTE = bytes.fromhex("21")
    P2SH_VERBYTES = [bytes.fromhex("08")]
    WIF_BYTE = bytes.fromhex("80")
    GENESIS_HASH = ('b7f315f768678c3c5b27bd43adeb0ce935ea8f0e22b976d1da13686038ce9665')
    RPC_PORT = 19119
    TX_COUNT = 0
    TX_COUNT_HEIGHT = 0
    TX_PER_BLOCK = 0
    VALUE_PER_COIN = 1000000
    REORG_LIMIT = 800
```

But then I get the following messages in the log:

```
INFO:Prefetcher:catching up to daemon height 2,114,530 (2,114,531 blocks behind)
INFO:Prefetcher:verified genesis block with hash a60ac43c88dbc44b826cf315352a8a7b373d2af8b6e1c4c4a0638859c5e9ecd1
WARNING:BlockProcessor:daemon blocks do not form a chain; resetting the prefetcher
```

I also don't know what the correct values of
```
    TX_COUNT = 0
    TX_COUNT_HEIGHT = 0
    TX_PER_BLOCK = 0
```

could be?

**Comment by smogm** [comment]
More infos similar to this issue:
https://github.com/kyuupichan/electrumx/issues/423

**Comment by smogm** [comment]
Okay, got it to work :+1: 
blockhash is scrypt

This is the class to be added to lib/coins.py
```
class ECCoin(Coin):
    NAME = "ECCoin"
    SHORTNAME = "ECC"
    NET = "mainnet"
    DESERIALIZER = lib_tx.DeserializerTxTime
    XPUB_VERBYTES = bytes.fromhex("0488b21e")
    XPRV_VERBYTES = bytes.fromhex("0488ade4")
    P2PKH_VERBYTE = bytes.fromhex("21")
    P2SH_VERBYTES = [bytes.fromhex("08")]
    WIF_BYTE = bytes.fromhex("80")
    GENESIS_HASH = ('a60ac43c88dbc44b826cf315352a8a7b373d2af8b6e1c4c4a0638859c5e9ecd1')
    RPC_PORT = 19119
    TX_COUNT = 0
    TX_COUNT_HEIGHT = 0
    TX_PER_BLOCK = 0
    VALUE_PER_COIN = 1000000
    REORG_LIMIT = 800

    @classmethod
    def header_hash(cls, header):
        import scrypt
        return scrypt.hash(header, header, 1024, 1, 1, 32)
```

**Comment by HenryYoung42** [comment]
That is really neat. The Electrumx dev did a good job.

**Comment by smogm** [comment]
Another fix was necessary.
Starting with block `#1942731` with hash `0bbb5407a3235f219febf42e713223944b2273a7a496c908a5562ced64c3ee4b` first version 2 transactions were introduced.
Those have a "service reference hash" appended. It was necessary to skip those to make it working, adding this new class to lib/tx.py:

```
class DeserializerECCoin(Deserializer):
    def read_tx(self):
        tx_version = self._read_le_int32()
        tx = TxTime(tx_version, self._read_le_uint32(), self._read_inputs(), self._read_outputs(), self._read_le_uint32())

        if tx_version > 1:
             self.cursor += 32

        return tx
```

**Comment by HenryYoung42** [comment]
Details on SSL cert for Electrumx setup per @smogm @ Wire:
https://electrumx.readthedocs.io/en/latest/HOWTO.html#creating-a-self-signed-ssl-certificate

**Comment by smogm** [comment]
See this repo for currenct electrum **client** migration to ECC: https://github.com/smogm/electrum/commits/master

Current problem: The client can't compare the given checkpoint block header to the server side block header of the corresponding height.

The cause seems to be somewhere here: https://github.com/smogm/electrum/blob/master/electrum/blockchain.py#L534

It actually looks like a off-by-one error of the block height. But I didn't figure out where exactly...

**Comment by smogm** [comment]
With the following commit the electrum client is now fully working with ECC (generating addresses, receiving tx, sending tx...):
https://github.com/project-ecc/electrum-ecc/commit/a3f1ab48834f7ce2ae946979ec66a4f3c860bf79

What's now missing is maybe some cosmetics (replace all "bitcoin" strings and so on...)

**Comment by HenryYoung42** [comment]
Server config here https://github.com/project-ecc/electrum-ecc/blob/master/electrum/servers.json

**Comment by smogm** [comment]
Client and Server implemented.

**Comment by HenryYoung42** [comment]
Correction to OP which states that the following line should be run as a normal user. Actually it needs sudo privileges:

$ sudo python3 setup.py install

**Comment by smogm** [comment]
true, I worked with python virtualenv in the users home directory.
