### ISSUE TITLE
Evaluation: Pros & Cons for mimblewimble blockchain?

### ISSUE THREAD

**Issue by smogm** [project-ecc/issues#6]
**Introduction**
ECC is currently using the old fashion bitcoin-like blockchain consensus which is used in thousands of other projects as well.
It is the easiest approach to implement a decentralized consensus mechanism, but it has lots of drawbacks. 
The most prominents are scalability and fast increasing blockchain size which, on the long run, will sideline a large potential of full node operators (see ethereum, where you at the moment need a machine with at least 1 TB harddrive to only sync the blockchain, and it keeps growing rapidly).

mimblewimble is a blockchain technique where "old" or "overwritten" entries can be removed.
Example:
* tx1: PersonA sends x to PersonB
* tx2: PersonB sends x/2 to PersonC
* tx3: PersonB sends x/2 to PersonD

State after tx3: PersonB has 0 left from the amount it received from PersonA.
tx1 can be replaced by tx2 and tx3, resulting in the following state (this is called "Transaction Cut-Throughs"):
* tx1: PersonA sends x/2 to PersonC
* tx2: PersonA sends x/2 to PersonD

So one tx was removed and the overall blockchain state is still intact and consistent.

**Questions**

As @Greg-Griffith is already considering replacing the block-hash function scrypt by sha256, which will force a hard fork, we may have the chance to replace the whole blockchain mechanism with just a slight more effort?

- Do you think mimblewimble would be nice to have in ECC?
- How much work would have been done to implement mimblewimble?
- Is mimblewimble possible with PoS?
-

**Comment by HenryYoung42** [comment]
There is a further later of "compression" which can be applied to blockchains. It probably has a name, but I forget. The basic idea is to take all transactions on a block and build a single block transaction that has all the inputs and all the outputs of all transactions forming the block.
